// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcxanorldofcazuwefw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY3hhbm9ybGRvZmNhenV3ZWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTkzODAsImV4cCI6MjA3MDYzNTM4MH0.8VXT0AREBT0sZkUC2sMN0VXRCvs1i0Q4mSBhf9-2e6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});